nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:30009', 'http://localhost:8009', '*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
